### ISSUE TITLE
Fallback replies not at the right level in OIML.

### ISSUE THREAD

**Issue by clems4ever** [open-intent-io/open-intent#19]
Let say you branch two intent from one state, you only want one fallback reply if none of the intents has matched. Today there is one fallback reply by intent. 
How do we do to choose the right fallback reply?

I think the fix could be to add it at the level of the state instead of the level of the intent.

**Comment by eliteWalrus4164** [comment]
The fallback replies attach to the source state, they cannot attach to an edge, because passing in an edge, means an intent has been detected.
You mean that the notation is misleading perhaps?

**Comment by clems4ever** [comment]
This is what I meant. The fallback reply should be attached to the state not the edge as it is right now. The notation is not misleading at all but consider this use case: The user must choose between 'yes' and 'no'. If he says something else there should only be one possible fallback, right? Let's implement it.

{
@start
    -yes
        #action1
        *Don't understand1
    -You said yes.
@end
}

{
@start
    -no
        #action2
        *Don't understand2
    -You said no.
@end
}

We have 2 fallback replies in the implementation. This is not expected.

**Comment by eliteWalrus4164** [comment]
As I said, the fallback reply is already attached to the state.

**Comment by clems4ever** [comment]
What is the expected fallback reply if I say 'hey'? Don't understand1 or Don't understand2?

**Comment by eliteWalrus4164** [comment]
it's undefined for now, in the same way as if you attach it two times against a given state as in : 
{
@start
*Don't understand1
-yes
#action1
-You said yes.
@end
}

{
@start
*Don't understand2
-no
#action2
-You said no.
@end
}

**Comment by clems4ever** [comment]
It's very true.
