### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by Droppix** [open-intent-io/open-intent#52]
Hello,

Intéressant, mais je pense qu'une intégration sous forme de NPMJS serait plus intéressante.

**Comment by clems4ever** [comment]
Bonjour @RobertNNms, 

En réalité c'est déjà un package npm qui est intégré dans docker. Tu peux déployer un bot sur heroku uniquement avec du Node.js en suivant le tuto du lien suivant: https://github.com/open-intent-io/open-intent/wiki/Full-chatbot-deployment-tutorial.
@SergeKireev va mettre à jour le README pour que ce soit plus clair. 

N'hésite pas à nous faire tes retours si tu testes le framework. Ca serait top.

Merci.
Clément.
